from stateoftheuniverse.widgets.ephem_bodies import EphemBodies
from stateoftheuniverse.widgets.moon_phase_widget import MoonPhaseWidget
from stateoftheuniverse.widgets.constellations import ConstellationsWidget
from stateoftheuniverse.widgets.ExoplanetCount import ExoplanetCount
from stateoftheuniverse.widgets.AsteroidCount import AsteroidCount
from stateoftheuniverse.widgets.AstronomerBirthdays import AstronomerBirthdays
